apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ideaboard
type: Opaque
stringData:
  database-password: "ngdev@2024#"
  # In production, use Sealed Secrets or External Secrets Operator
  database-url: "postgresql://ngadmin:ngdev%402024%23@ng-central-dev-server.postgres.database.azure.com:5432/ng-central-dev-db?sslmode=require"