apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ideaboard
data:
  DATABASE_HOST: "ng-central-dev-server.postgres.database.azure.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ng-central-dev-db"
  DATABASE_USER: "ngadmin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ideaboard
data:
  REACT_APP_API_URL: "https://simpletwist.dpdns.org/api"
  REACT_APP_ENVIRONMENT: "production"