apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idea-board-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nikhilmulinti/idea-board
    targetRevision: main
    path: deploy-as-code/argocd
    directory:
      recurse: false
      include: '*-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false