apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.secrets.DATABASE_PASSWORD | quote }}
  database-url: "postgresql://{{ .Values.env.DATABASE_USER }}:{{ .Values.secrets.DATABASE_PASSWORD | urlquery }}@{{ .Values.env.DATABASE_HOST }}:{{ .Values.env.DATABASE_PORT }}/{{ .Values.env.DATABASE_NAME }}?sslmode=require"