apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - namespace.yaml

patchesStrategicMerge:
  - argocd-server-patch.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
      - server.basehref=/argocd
      - server.rootpath=/argocd