# Development Environment Configuration
letsencrypt:
  email: nikhil.mulinti@gmail.com

argocd:
  host: argocd.simpletwist.dpdns.org

app:
  host: simpletwist.dpdns.org

github:
  repo: https://github.com/nikhilmulinti/idea-board

postgresql:
  host: hcm-dev-server.postgres.database.azure.com
  database: hcm-dev-db
  username: hcmadmin
  password: "hcmdev@2024"

# Cloud-specific configurations
# Uncomment and modify based on your cloud provider

# For Azure:
ingress:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

# For AWS:
# ingress:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb

# For GCP:
# ingress:
#   annotations:
#     cloud.google.com/load-balancer-type: External